package net.joostit.winchhunt.controllers;

import net.joostit.winchhunt.entities.Site;
import net.joostit.winchhunt.repositories.SiteRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/")
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private SiteRepository siteRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Site n = new Site();
        n.setName(name);
        n.setEmail(email);
        siteRepository.save(n);
        return "Saved";
    }

    @GetMapping("/{link}")
    public String index(@PathVariable String link, Model model) {

        if(link == null){
            link = "home";
        }

        model.addAttribute("viewTargetPath", "articles/" + link + "view");
        model.addAttribute("viewTargetName", link + "view");

        return "layout";
    }

    @GetMapping("/")
    public String index(Model model) {
        return index(null, model);
    }


    @GetMapping(path="/all")
    public @ResponseBody Iterable<Site> getAllUsers() {
        // This returns a JSON or XML with the users
        return siteRepository.findAll();
    }
}