spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_jwinchhunt
spring.datasource.username=winchhuntappuser
spring.datasource.password=TheWinchHuntDevPassWord